### ISSUE TITLE
VideoPlayer doesn't work with TV remote

### ISSUE THREAD

**Issue by VincentKos** [jepiqueau/jeep#2]
Hello,

the player work great and i'm able to play video on my tv but i can't use any control (forward, backward, play, pause, stop). I can't quit the video without quitting the app.

Any fix avaible ?

**Comment by jepiqueau** [comment]
Are you running the Plugin on IOS, Android or web ?
I never test it on a tv so tell me what platform are you running it from. I could test web an android on tv but not IOS as i do not have any ios mobile.

**Comment by VincentKos** [comment]
it's on my android tv. The video work great but controls doesn't work at all and I can't close/leave the video.

**Comment by jepiqueau** [comment]
@VincentKos this issue has been addressed so i close it
