### ISSUE TITLE
error: package android.support.v7.app does not exist

### ISSUE THREAD

**Issue by rasyidialwee** [jepiqueau/jeep#32]
Hello i try the Video Player and its working fine on web
but when i try to compile on android i got appcompat error

error: package android.support.v7.app does not exist
import android.support.v7.app.AppCompatActivity;

**Comment by jepiqueau** [comment]
@rasyidialwee Sorry you are looking at a really old release from here. On the advise on the Capacitor team i split up all my 3 plugins. go to `https://github.com/jepiqueau/capacitor-video-player` and look at the apps starter. to install it run `npm install --save capacitor-video-player@latest` and for Android  in your app go to the `MainActivity.java` file and add the import and the class declaration as follow:
```
import com.jeep.plugin.capacitor.CapacitorVideoPlayer;

public class MainActivity extends BridgeActivity {

  @Override
  public void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);

    // Initializes the Bridge
    this.init(
        savedInstanceState,
        new ArrayList<Class<? extends Plugin>>() {

          {
            // Additional plugins you've installed go here
            // Ex: add(TotallyAwesomePlugin.class);
            add(CapacitorVideoPlayer.class);
          }
        }
      );
  }
}
```

**Comment by rasyidialwee** [comment]
> @rasyidialwee Sorry you are looking at a really old release from here. On the advise on the Capacitor team i split up all my 3 plugins. go to `https://github.com/jepiqueau/capacitor-video-player` and look at the apps starter. to install it run `npm install --save capacitor-video-player@latest` and for Android in your app go to the `MainActivity.java` file and add the import and the class declaration as follow:
> 
> ```
> import com.jeep.plugin.capacitor.CapacitorVideoPlayer;
> 
> public class MainActivity extends BridgeActivity {
> 
>   @Override
>   public void onCreate(Bundle savedInstanceState) {
>     super.onCreate(savedInstanceState);
> 
>     // Initializes the Bridge
>     this.init(
>         savedInstanceState,
>         new ArrayList<Class<? extends Plugin>>() {
> 
>           {
>             // Additional plugins you've installed go here
>             // Ex: add(TotallyAwesomePlugin.class);
>             add(CapacitorVideoPlayer.class);
>           }
>         }
>       );
>   }
> }
> ```

Hello thanks for redirecting me.
