### ISSUE TITLE
[CapacitorSqlite]: plugin CapacitorSqlite is undefined on Android

### ISSUE THREAD

**Issue by slevy85** [jepiqueau/jeep#5]
I try to use CapacitorSqlite plugin but it is undefined on Android, i followed the documentation :  
- I installed the plugin with yarn
- I synchronize capacitor : `npx cap sync android`
- I build the project and copy to android
- I declared the plugin in `MainActivity.java` :  
```
 this.init(savedInstanceState, new ArrayList<Class<? extends Plugin>>() {{
      // Additional plugins you've installed go here
      // Ex: add(TotallyAwesomePlugin.class);
       add(CapacitorSQLite.class);
       add(CapacitorDataStorageSqlite.class);
   }});
```
I use also `CapacitorDataStorageSqlite` the same way and this one is not undefined.

```
const { CapacitorDataStorageSqlite, CapacitorSqlite } = Plugins;

console.log('CapacitorSqlite : ' + CapacitorSqlite); // undefined
console.log('CapacitorDataStorageSqlite : ' + CapacitorDataStorageSqlite); // [object object]
```
I can see in the log the plugin is registered by capacitor :  
```
(more logs)
D/Capacitor: Registering plugin: StatusBar
D/Capacitor: Registering plugin: Storage
D/Capacitor: Registering plugin: Toast
D/Capacitor: Registering plugin: WebView
D/Capacitor: Registering plugin: CapacitorSQLite
D/Capacitor: Registering plugin: CapacitorDataStorageSqlite
```
Do you have an idea about this ?

**Comment by jepiqueau** [comment]
the plugin is CapacitorSQLite and not  CapacitorSqlite

**Comment by slevy85** [comment]
Ahah thank you very much I am sorry about this.

**Comment by jepiqueau** [comment]
No problems you are wellcome
