### ISSUE TITLE
sqlite performance and stability (vs cordova-sqlite-ext)

### ISSUE THREAD

**Issue by chriswep** [jepiqueau/jeep#6]
This is more a question than an issue, however it might be relevant for others searching for this.

How would using this plugin for SQLite compare to something like https://github.com/brodybits/cordova-sqlite-ext? Would you expect better performance? What about stability (the mentioned cordova plugin has a long history and lots of optimisations / fixes going into it)?

**Comment by jepiqueau** [comment]
@chriswep first thank you for the comment. It is hard to answer, but what is good for developers is that the two technologies are available and both can be used with mobile frameworks. For developers starting mobile development or looking for stability, the easiest way is to use cordova plugins, they will not have to understand or even care about Android Studio, Xcode, Java or Swift. For those who want to understand what's going on and be closest to the native applications they will choose Ionic Capacitor plugins.
Having said that, it is just my opinion.
When Ionic comes with Capacitor, i was just curious about this and as i love new technologies, i decided to look at it. But to look at something you have to fix you a challenge. So i decided to go for a capacitor data storage sqlite plugin which for me was important for storing application states or other data in a permanent basis on mobile. Not knowing, Capacitor, Swift, Android and neither Android Studio and Xcode, it took me 2 weeks to come with a first release. So i found it amazing. 
After this, people when starting to ask for an sqlite plugin and have encryption feature so i looked at it and provide it. I didn't look at that time if similar cordova plugin was existing.
about performance, i never made any test so i do not know
about stability, the one with a long history should be more stable for sure. i try to resolve all the issues coming as fast as i can.
Sorry, if my answer is not good enough. It should be seen as an alternative. It was just fun to do it
